// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeInternship.Infrastructure.Data;

#nullable disable

namespace PracticeInternship.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PracticeInternshipDbContext))]
    [Migration("20250115030216_updateSentence7")]
    partial class updateSentence7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Don_Vi_Tinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_Don_Vi_Tinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DM_Don_Vi_Tinh");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Kho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_Kho")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DM_Kho");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Kho_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Kho_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma_Dang_Nhap")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Kho_Id");

                    b.HasIndex("Ma_Dang_Nhap", "Kho_Id")
                        .IsUnique()
                        .HasFilter("[Ma_Dang_Nhap] IS NOT NULL");

                    b.ToTable("DM_Kho_User");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Loai_San_Pham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_LSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_LSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DM_Loai_San_Pham");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_NCC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_NCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_NCC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DM_NCC");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Nhap_Kho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Kho_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NCC_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Ngay_Nhap_kho")
                        .HasColumnType("datetime2");

                    b.Property<string>("So_Phieu_Nhap_Kho")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Kho_Id");

                    b.HasIndex("NCC_Id");

                    b.ToTable("DM_Nhap_Kho");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Nhap_Kho_Raw_Data", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Don_Gia_Nhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Nhap_Kho_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SL_Nhap")
                        .HasColumnType("int");

                    b.Property<Guid>("San_Pham_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Nhap_Kho_Id");

                    b.HasIndex("San_Pham_Id");

                    b.ToTable("DM_Nhap_Kho_Raw_Data");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_San_Pham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Don_Vi_Tinh_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Loai_San_Pham_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma_San_Pham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_San_Pham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Don_Vi_Tinh_Id");

                    b.HasIndex("Loai_San_Pham_Id");

                    b.ToTable("DM_San_Pham");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Kho_User", b =>
                {
                    b.HasOne("PracticeInternship.Domain.Entities.DM_Kho", "DM_Kho")
                        .WithMany("DM_Kho_User")
                        .HasForeignKey("Kho_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DM_Kho");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Nhap_Kho", b =>
                {
                    b.HasOne("PracticeInternship.Domain.Entities.DM_Kho", "DM_Kho")
                        .WithMany("DM_Nhap_Kho")
                        .HasForeignKey("Kho_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeInternship.Domain.Entities.DM_NCC", "DM_NCC")
                        .WithMany("DM_Nhap_Kho")
                        .HasForeignKey("NCC_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DM_Kho");

                    b.Navigation("DM_NCC");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Nhap_Kho_Raw_Data", b =>
                {
                    b.HasOne("PracticeInternship.Domain.Entities.DM_Nhap_Kho", "DM_Nhap_Kho")
                        .WithMany("DM_Nhap_Kho_Raw_Data")
                        .HasForeignKey("Nhap_Kho_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeInternship.Domain.Entities.DM_San_Pham", "DM_San_Pham")
                        .WithMany("DM_Nhap_Kho_Raw_Data")
                        .HasForeignKey("San_Pham_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DM_Nhap_Kho");

                    b.Navigation("DM_San_Pham");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_San_Pham", b =>
                {
                    b.HasOne("PracticeInternship.Domain.Entities.DM_Don_Vi_Tinh", "DM_Don_Vi_Tinh")
                        .WithMany("DM_San_Pham")
                        .HasForeignKey("Don_Vi_Tinh_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticeInternship.Domain.Entities.DM_Loai_San_Pham", "DM_Loai_San_Pham")
                        .WithMany("DM_San_Pham")
                        .HasForeignKey("Loai_San_Pham_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DM_Don_Vi_Tinh");

                    b.Navigation("DM_Loai_San_Pham");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Don_Vi_Tinh", b =>
                {
                    b.Navigation("DM_San_Pham");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Kho", b =>
                {
                    b.Navigation("DM_Kho_User");

                    b.Navigation("DM_Nhap_Kho");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Loai_San_Pham", b =>
                {
                    b.Navigation("DM_San_Pham");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_NCC", b =>
                {
                    b.Navigation("DM_Nhap_Kho");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_Nhap_Kho", b =>
                {
                    b.Navigation("DM_Nhap_Kho_Raw_Data");
                });

            modelBuilder.Entity("PracticeInternship.Domain.Entities.DM_San_Pham", b =>
                {
                    b.Navigation("DM_Nhap_Kho_Raw_Data");
                });
#pragma warning restore 612, 618
        }
    }
}
